### ISSUE TITLE
EC Encryption with generated shared key

### ISSUE THREAD

**Issue by VishnuV02** [104corp/JOSE-ECDH-ES-Swift#2]
Hi, 

How to get generated public key from JOSE-ECDH-ES-Swift library, because i have to pass generated public key to server.

**Comment by mfantcy** [comment]
here example
```swift
let serverKeyPair = try! generateECKeyPair(curveType: .P256)
let serverPublicKey = serverKeyPair.getPublic()
let serverPublicJWKJsonStr = serverPublicKey!.jsonString()
```

**Comment by mfantcy** [comment]
Conceptually
The sender encrypts with the recipient's public key.
The recipient decrypts using the private key corresponding to the encrypted public key.

**Comment by VishnuV02** [comment]
If i use generateECKeyPair, it will produce new key pair right? But i want to send the public key you generated internally.

**Comment by VishnuV02** [comment]
As you mentioned, The recipient decrypts using the private key corresponding to the encrypted public key. Kindly let me know how to get that public key to send to server?

**Comment by mfantcy** [comment]
If You mean ephemeral Public Key
It is already in the header of JWE `epk `

**Comment by VishnuV02** [comment]
This is the code i followed,

        let plaintext = "test".data(using: .utf8)!
        
        let ServerpubJwk = """
        {
            "crv": "P-256",
            "kty": "EC",
            "x": "CQJxA68WhgU3hztigbedfLtJitDhScq3XSnXgO0FV5o",
            "y": "WFg6s36izURa733WqeoJ8zXMd7ho5OSwdWnMsEPgTEI"
        }
        """
        
        let encryptionJwe = try! EcdhEsJwe(plaintext: plaintext, pubKeyJwkJson: ServerpubJwk, headerDic: ["alg": "ECDH-ES", "enc": "A256GCM"])
        
        print(encryptionJwe.header.epk?.jsonString() as Any)
        print(encryptionJwe.encryptedKey)

In this encryptionJwe.header.epk output is 
Optional(JOSESwift.ECPublicKey(keyType: JOSESwift.JWKKeyType.EC, parameters: ["crv": "P-256", "kid": "CC5A1B5E-6922-4C87-A9B8-6EBE6C53650D", "x": "hnc_K9IakeFyRuAHFIaIR3tnH5vtv10uxY8MrFIBZBU", "y": "ntyEBWuAFqVH059Mr-y7D7DqtRfIF-xRc4jePZWL3-I", "kty": "EC"], crv: JOSESwift.ECCurveType.P256, x: "hnc_K9IakeFyRuAHFIaIR3tnH5vtv10uxY8MrFIBZBU", y: "ntyEBWuAFqVH059Mr-y7D7DqtRfIF-xRc4jePZWL3-I"))
ECPublicKey(keyType: JOSESwift.JWKKeyType.EC, parameters: ["d": "MyuVCuK2QnYhZ5kzUZfF_csl6IZQBvJlDSv5skHyF3k", "y": "ntyEBWuAFqVH059Mr-y7D7DqtRfIF-xRc4jePZWL3-I", "kty": "EC", "x": "hnc_K9IakeFyRuAHFIaIR3tnH5vtv10uxY8MrFIBZBU", "kid": "CC5A1B5E-6922-4C87-A9B8-6EBE6C53650D", "crv": "P-256"], crv: JOSESwift.ECCurveType.P256, x: "hnc_K9IakeFyRuAHFIaIR3tnH5vtv10uxY8MrFIBZBU", y: "ntyEBWuAFqVH059Mr-y7D7DqtRfIF-xRc4jePZWL3-I")
Optional("{\"kid\":\"CC5A1B5E-6922-4C87-A9B8-6EBE6C53650D\",\"y\":\"ntyEBWuAFqVH059Mr-y7D7DqtRfIF-xRc4jePZWL3-I\",\"x\":\"hnc_K9IakeFyRuAHFIaIR3tnH5vtv10uxY8MrFIBZBU\",\"kty\":\"EC\",\"crv\":\"P-256\"}")

So you mean to say i have to send the encryptionJwe.header.epk?.jsonString() to server right?

**Comment by VishnuV02** [comment]
Please tell me how to get private key, because i have to decrypt the response from server with the concerned private key.

**Comment by mfantcy** [comment]
You don't need to send epk
It's already in your encrypted JWE

The encrypted party must be encrypted using the corresponding public key of the decrypting party.
The decrypted party can decrypt it with the private key.

Can you let me know your scenario?

The general usage scenario is that the client transmits the ciphertext to the server.
The server must have a key pair (private key and the corresponding public key).
The server exposes the public key, so that the client that intends to transfer the ciphertext to the server uses this public key to encrypt.

**Comment by VishnuV02** [comment]
My Scenario:
1) I have to send compactserializedString  as well as EpermalPublickey to server separately.
2) Server will decrypts.
3) Server again send encrypted response back to Client.
4) Client will decrypts the response with the Epermalprivatekey.

**Comment by mfantcy** [comment]
OK I see

Here is an options attribute "ephemeralKeyPair"
Ephemeral key pair can be specified without being randomly generated by this lib

for example (modified from your code)
```swift
let ephemeralKeyPair = try! generateECKeyPair(curveType: .P256)

let plaintext = "test".data(using: .utf8)!

let ServerpubJwk = """
{
    "crv": "P-256",
    "kty": "EC",
    "x": "CQJxA68WhgU3hztigbedfLtJitDhScq3XSnXgO0FV5o",
    "y": "WFg6s36izURa733WqeoJ8zXMd7ho5OSwdWnMsEPgTEI"
}
"""

let encryptionJwe = try! EcdhEsJwe(plaintext: plaintext, pubKeyJwkJson: ServerpubJwk, headerDic: ["alg": "ECDH-ES", "enc": "A256GCM"], options: ["ephemeralKeyPair": ephemeralKeyPair])

```

**Comment by VishnuV02** [comment]
Thank you for your solution! Your solution helped me a lot!
